2003/tech 4206 convert invoca utils to gemfury
Invoca/invoca-utils pull request #8
Opened 2020-03-05 18:39 UTC by rphammy

2020-03-05 22:06 UTC, dtognazzini requested changes
Looks like this gem is public:
https://rubygems.org/gems/invoca-utils

So.. we should be publishing this gem to Rubygems, not Gemfury.

2020-03-05 22:13 UTC, ColinDKelley commented on invoca-utils.gemspec
> +  spec.metadata['allowed_push_host'] = "https://gem.fury.io/invoca"
I prefer this notation because it doesn't mutate, and in case there is other metadata to set in the future:
```
spec.metadata = {
  "allowed_push_host" => "...rubygems..."
}
```

2020-03-05 23:28 UTC, ColinDKelley commented on lib/invoca/utils/version.rb
>  module Invoca
This is is because the`# frozen_string_literal: true` comment is missing at the top.

2020-03-05 23:30 UTC, ColinDKelley commented on lib/invoca/utils/version.rb
>  module Invoca
It wouldn't hurt to `gem install` and run this utility over the repo:

https://github.com/invoca/magic_frozen_string_literal#magic_frozen_string_literal-

2020-03-12 22:11 UTC, ColinDKelley approved these changes

2020-03-13 17:19 UTC, dtognazzini approved these changes

2020-03-13 20:44 UTC, merged